<?php

namespace WhackUp\UserBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    /*
    public function nbreDisco()
    {
        $qb = $this
            ->createQueryBuilder('d')  //SELECT COUNT(d) FROM WhackUpManageBundle:Disco
            ->select('COUNT(d)');
        ;

        $result = $qb->getQuery()->getSingleScalarResult();

        return $result;
    }
    */
}
