# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        WhackUp\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_USER_PRENIUM:  ROLE_USER
        ROLE_SUPER_ADMIN:   ROLE_ADMIN

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

        main_user:
            id: fos_user.user_provider.username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        un_secured_whackup_admin:
            pattern:  ^/(admin/login)$
            anonymous: true

        secured_whackup_admin:
            pattern:    ^/admin/
            anonymous: false
            provider : main_user
            form_login:
                login_path: admin_login
                check_path: admin_login_check
                default_target_path: /admin/
            logout:
                path:   admin_logout
                target: admin_login

        un_secured_whackup_user:
            pattern:   ^/(login|register/)$
            anonymous: true # On autorise alors les anonymes sur ce pare-feu

        secured_whackup_user:
            pattern:   ^/
            anonymous: false
            provider:  main_user
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
            logout:
                path:   fos_user_security_logout
                target: fos_user_security_login
            # remember_me: whack_up
            #     key:    %secret%

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, role: ROLE_USER }
        - { path: ^/admin/, role: ROLE_ADMIN }


