# src/WhackUp/ManageBundle/Ressources/config/routing.xml

whack_up_manage_homepage:
    path:     /
    defaults: { _controller: WhackUpManageBundle:Disco:index }

whack_up_manage_disco:
    path:     /disco
    defaults: { _controller: WhackUpManageBundle:Disco:index }

whack_up_manage_add_disco:
    path:     /disco/add
    defaults: { _controller: WhackUpManageBundle:Disco:add }

whack_up_manage_view_disco:
    path:     /disco/{id}/view
    defaults: { _controller: WhackUpManageBundle:Disco:view }
    requirements:
       id : \d*
whack_up_manage_edit_disco:
    path:     /disco/{id}/edit
    defaults: { _controller: WhackUpManageBundle:Disco:edit }
    requirements:
       id : \d*

whack_up_manage_edit_disco_image:
    path:     /disco/{id}/edit/image
    defaults: { _controller: WhackUpManageBundle:Disco:editimage }
    requirements:
       id : \d*

whack_up_manage_pub:
    path:     /advert
    defaults: { _controller: WhackUpManageBundle:Advert:index }

whack_up_manage_pub_add:
    path:     /advert/add
    defaults: { _controller: WhackUpManageBundle:Advert:add }


admin_login:
    path:  /login
    defaults: { _controller: WhackUpManageBundle:Security:login }

admin_login_check:
    path:  /login_check
    defaults: { _controller: WhackUpManageBundle:Security:check }   #FOSUserBundle

admin_logout:
    path:  /logout
    defaults: { _controller: FOSUserBundle:Security:logout }

admin_profile:
    path:  /profile
    defaults: { _controller: FOSUserBundle:Profile:show }

admin_profile_edit:
    path:  /profile/edit
    defaults: { _controller: FOSUserBundle:Profile:edit }

admin_param:
    path:  /parameters
    defaults: { _controller: WhackUpUserBundle:Profile:parameter }

admin_avatar:
    path:  /picture
    defaults: { _controller: WhackUpUserBundle:Profile:picture }

admin_change_password:
    path:  /profile/change-password
    defaults: { _controller: WhackUpUserBundle:ChangePassword:changePassword }
