<?php

namespace WhackUp\ManageBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function nbreAdvert()
    {
        $qb = $this
            ->createQueryBuilder('a')
            ->select('COUNT(a)');
        ;

        $result = $qb->getQuery()->getSingleScalarResult();

        return $result;
    }

    public function findActually($fire){
        $qb = $this->createQueryBuilder('a');

        $qb->where('a.actived = :act')
            ->setParameter('act', $fire)
            ->orderBy('a.dateEnd', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
            ;
    }
}
