<?php

namespace WhackUp\ManageBundle\Repository;


use Doctrine\ORM\QueryBuilder;

/**
 * DiscoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DiscoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     * return nomber of night club created
     */
    public function nbreDisco()
    {
        $qb = $this
            ->createQueryBuilder('d')  //SELECT COUNT(d) FROM WhackUpManageBundle:Disco
            ->select('COUNT(d)');
        ;

        $result = $qb->getQuery()->getSingleScalarResult();

        return $result;
    }

    /**
     * @return mixed
     * get by name
     */
    public function findByNameDisco($key)
    {
        $qb = $this
            ->createQueryBuilder('d')
            ->where('d.nom LIKE :nom')
            ->setParameter('nom','%'.$key.'%')
        ;

        $result = $qb->getQuery()->getResult();  //

        return $result;
    }

    public function nbreByNameDisco($key)
    {
        $qb = $this
            ->createQueryBuilder('d')
            ->select('COUNT(d)')
            ->where('d.nom like :nom')
            ->setParameter('nom','%'.$key.'%')
        ;

        $result = $qb->getQuery()->getSingleScalarResult();

        return $result;
    }
}
