<?php

namespace WhackUp\ManageBundle\Repository;

/**
 * ImageDiscoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageDiscoRepository extends \Doctrine\ORM\EntityRepository
{
}
